# Default values for application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:
  - name: ghcr-pull-secret

env:
  - name: REDIS_HOST
    value: redis-headless
  - name: REDIS_PORT
    value: "6379"

# Secret name suffix => Vault path
vaultSecrets:
  - croatia-police/app-env

service:
  type: ClusterIP
  name: http
  port: &servicePort 5000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:683089476926:certificate/00f8a2ef-b500-42c2-8f80-2dd1e18e84da
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: app-integrations
    alb.ingress.kubernetes.io/healthcheck-port: '5000'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
  hosts:
    - host: croatia-police.app-integrations.cloudbeds-dev.com
      paths:

        - path: /
          pathType: ImplementationSpecific
          serviceName: ssl-redirect
          servicePortName: use-annotation

        - path: /*
          pathType: ImplementationSpecific
          serviceName: croatia-police
          servicePortNumber: *servicePort

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi


redis:
  enabled: true
