{{- range .Values.vaultSecrets }}
{{- $key := ( . | replace $.Release.Name "" | replace "/" "" ) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "croatia-police.fullname" $ }}-{{ $key }}
  labels:
    {{- include "croatia-police.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ . | quote }}
  {{- end }}
