apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: croatia-police
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: croatia-police
  destination:
    server: https://kubernetes.default.svc
    namespace: croatia-police
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  sources:
    - repoURL: https://github.com/cloudbeds-integrations/croatia-police
      path: _argocd/charts/croatia-police
      targetRevision: main
      helm:
        releaseName: croatia-police
        valueFiles:
          - $values/_argocd/charts/croatia-police/values-dev.yaml
        values: |
          image:
            tag: 6e61f318972d8f3998a5679ac3d901d827754fd6
    - repoURL: https://github.com/cloudbeds-integrations/croatia-police
      targetRevision: main
      ref: values
