apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: croatia-police
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: croatia-police
  destination:
    server: https://kubernetes.default.svc
    namespace: croatia-police
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  source:
    repoURL: https://github.com/cloudbeds-integrations/croatia-police
    path: _argocd/charts/croatia-police
    targetRevision: main
    helm:
      releaseName: croatia-police
      valueFiles:
        - values-dev.yaml
