apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps-croatia-police
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: fastapi=ghcr.io/cloudbeds-integrations/croatia-police/app:*
    argocd-image-updater.argoproj.io/fastapi.update-strategy: latest
    argocd-image-updater.argoproj.io/fastapi.allow-tags: regexp:[0-9a-f]{5,40}
spec:
  project: croatia-police
  destination:
    server: https://kubernetes.default.svc
    namespace: croatia-police
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  source:
    repoURL: https://github.com/cloudbeds-integrations/croatia-police
    path: _argocd/charts/croatia-police
    targetRevision: main
    helm:
      releaseName: croatia-police
      valueFiles:
        - values-dev.yaml
