name: Package Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - _argocd/**  # <<<< !!! Very Important exclusion, otherwise there is a danger of endless loop build and deploy
      - .github/**
      - docker-compose.yml
      - Makefile
      - README.md

jobs:

  build-push:
    name: Build & Publish Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.event.repository.full_name }}/app:${{ github.sha }}
            ghcr.io/${{ github.event.repository.full_name }}/app:latest
