name: Pull Request

on:
  pull_request:

jobs:
  code-testing:
    name: Code testing
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unit test
        run: |
          echo "place to add your unit test steps"
