name: Re-tag images and Publish

# Release tags with suffix -rc are deployed to staging and without to production
on:
  push:
    tags:
      - 'v*'

env:
  CRANE_VERSION: v0.16.1
  CRANE_SHA_HASH: 115dc84d14c5adc89c16e3fa297e94f06a9ec492bb1dc730da624850b77c9be2

jobs:

  re-tag:
    name: Re-tag images
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:

      - name: Login to Container Registry
        # Release v3.0.0 https://github.com/docker/login-action/commit/343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install crane
        run: |
          set -ex
          echo "Installing crane version ${{ env.CRANE_VERSION }}"
          curl -sLO https://github.com/google/go-containerregistry/releases/download/${{ env.CRANE_VERSION }}/go-containerregistry_Linux_x86_64.tar.gz
          echo "${{ env.CRANE_SHA_HASH }} go-containerregistry_Linux_x86_64.tar.gz" | sha256sum -c
          sudo tar -xzf ./go-containerregistry_Linux_x86_64.tar.gz -C /usr/local/bin crane
          rm ./go-containerregistry_Linux_x86_64.tar.gz

      - name: Re-tag image(s)
        run: |
          crane tag "ghcr.io/${{ github.event.repository.full_name }}/app:${{ github.sha }}" "${{ github.ref_name }}"
